service: blog-github-actions
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1


package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello_world:
    handler: handler.hello_world
    events:
      - http:
          path: hello
          method: get
